### ISSUE TITLE
Update packages to resolve vulnerabilities

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-react-app-playground#42]
### Issue description
There are about 7000+ vulnerabilities based on npm audit. All of these are in the tooling, not in the built app. However, it gets annoying sifting through the list in order to see if there are app issues.

> **ESTIMATE** 2

#### Tasks
- [x] Task: run `npm audit fix`
- [x] Spike: document packages that need version updating for each app -> tickets for resolving individual packages

**Comment by bryanpizzillo** [comment]
This is going to be a multi-commit fix. An initial `npm audit fix` cuts down the number down to 18 that are semver changes. Trying some of the semver changes resulted in a broken app and failing tests.

**Comment by seyilonge-nci** [comment]
- An `npm audit` report generated the file attached below
[react-app-playground-audit.txt](https://github.com/NCIOCPL/cgov-react-app-playground/files/9558611/react-app-playground-audit.txt)

- Ran `npm audit fix` successfully with console output attached below
[npm-audit-fix-result.txt](https://github.com/NCIOCPL/cgov-react-app-playground/files/9558718/npm-audit-fix-result.txt)

- `npm run test` ran successfully with no errors

- Running `npm audit` generated file attached below
[report-after-npm-audit-fix.txt](https://github.com/NCIOCPL/cgov-react-app-playground/files/9558942/report-after-npm-audit-fix.txt)
