### ISSUE TITLE
Enabler: Publish main.css as a main-legacy.css for Redesign Support

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-react-app-playground#50]
# Publish main.css as a main-legacy.css for Redesign Support
> **ESTIMATE** 3

We need to publish a second copy of the main.css stylesheet for the www Redesign that has all selectors prefixed with `.cgdpl`. This class wraps the content and support the legacy www front-end CSS. The challenge is that since .cgdpl wraps all css for the new `Common.css`, those classes now have higher specificity than the React apps' CSS. For example what once was `h2 { foo: bar; }` is now `.cgdpl h2 {foo: bar; }`, which would win out for `.foo { bar: bazz }` that might style an `h2`.

## Solution
The following was prototyped for the CTS app and should work for all the apps.

1. `npm install --save-dev postcss-prefix-selector`
2. Create the script for creating the legacy css. Create this as `scripts/generate-cgdp-legacy.js`
     ```
     /* -------------------------------------------------------------------------
      * So we need to prefix all CTS css selectors with .cgdpl to support the
      * www redesign using ncids. Since our app manages its css with each
      * component, we can't just create a new entry point. Well, I guess we could
      * and just build the app twice and then do something, but that seems icky.
      * ------------------------------------------------------------------------- */
      'use strict';

      const path = require('path');
      const fs = require('fs');
      const appPaths = require('../config/paths');
      const postcss = require('postcss');
      const prefixer = require('postcss-prefix-selector');

      const inputFileName = path.join(appPaths.appBuild, '/static/css/main.css');
      const outputFileName = path.join(
        appPaths.appBuild,
        '/static/css/main-legacy.css'
      );

      try {
        const inputCss = fs.readFileSync(inputFileName, 'utf8');

        const outputCss = postcss()
          .use(
            prefixer({
              prefix: '.cgdpl',
            })
          )
          .process(inputCss).css;

        fs.writeFileSync(outputFileName, outputCss);
      } catch (err) {
        console.error(err);
      }     
     ```
3. Change the `"build": "node scripts/build.js",` script in package.json to be:
     ```
    "build:cgdp-legacy": "node scripts/generate-cgdp-legacy.js",
    "build:cra": "node scripts/build.js",
    "build": "npm run build:cra && npm run build:cgdp-legacy",
     ```

**Comment by sarinapadilla** [comment]
Closing this ticket, as the fixes were merged with PR #60!
